### ISSUE TITLE
'Sleepycat' store now 'BerkeleyDB'

### ISSUE THREAD

**Issue by wymmij** [nikita-moor/etymological-dictionary#1]
Just a heads-up that the BerkeleyDB store has now changed its name from `sleepycat` to `berkeleydb`.

Also, the direct download link for the dataset is now: [http://etym.org/etymwn-20130208.zip](http://etym.org/etymwn-20130208.zip)

**Comment by nikita-moor** [comment]
Thank you, fixed.
